version: '3'
services:
    web:
        build: ./etc/nginx
        container_name: markii-nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "${SOURCE_PATH}:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        restart: always
        env_file:
            - ".env"
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        depends_on:
            - php
            - mysqldb
    php:
        build: ./etc/php
        container_name: markii-php
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./${SOURCE_PATH}:/var/www/html"
        depends_on:
            - mysqldb
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: markii-phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:5.7.22
        container_name: markii-mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
